#!/bin/bash

echo "📸 开始演示阅读App并截图..."

# 确保应用在运行
if ! pgrep -f "yuedu_flutter" > /dev/null; then
    echo "启动应用..."
    cd "/home/shawnight/项目工作/book-reader"
    ./build/linux/x64/debug/bundle/yuedu_flutter > /dev/null 2>&1 &
    sleep 3
fi

echo ""
echo "📷 截图计划："
echo "  1. 书架页面（当前）"
echo "  2. 书源页面"
echo "  3. 设置页面"
echo ""
echo "✅ 应用已启动"
echo ""
echo "💡 手动操作提示："
echo ""
echo "查看书架："
echo "  • 当前显示空书架"
echo "  • 右上角🔍搜索按钮"
echo ""
echo "切换到书源标签："
echo "  • 点击底部【书源】"
echo "  • 右上角➕导入书源"
echo ""
echo "切换到设置标签："
echo "  • 点击底部【设置】"
echo "  • 主题/字体/关于"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 功能演示流程："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "第1步：导入书源"
echo "  → 书源标签 → 右上角+ → 选择书源.json"
echo ""
echo "第2步：搜索小说"
echo "  → 书架标签 → 右上角🔍 → 输入'斗破'"
echo "  → 显示搜索结果"
echo ""
echo "第3步：加入书架"
echo "  → 点击右侧⊕按钮 → 加入书架"
echo ""
echo "第4步：查看书架"
echo "  → 返回书架 → 显示收藏的书籍"
echo "  → 显示'读到：第X章'"
echo ""
echo "第5步：阅读小说"
echo "  → 点击书籍 → 选择章节 → 阅读"
echo "  • 左右滑动翻页"
echo "  • 点击屏幕显示控制栏"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📸 已保存截图：/tmp/yuedu_01_bookshelf.png"
echo ""
echo "🎉 应用运行中，可以手动操作查看效果！"
